version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.0
    - 8.1.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.166
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
